### PR TITLE
Update initializePromise error handling

### PR DESCRIPTION
**Pull request by a-robinson**
To bring it in line with the recent change in the docs repo:
https://github.com/cloudflare/cloudflare-docs/pull/1041

@xortive @koeninger

### CODE REVIEW

**Comment by a-robinson** [comment]
The configuration of this repo seems a bit messed up -- I don't have the same privileges on it as the other durable object templates, and it's also marked as a "Template" repo by Github.

**Comment by xortive** [comment]
@a-robinson can you update the binding format as well? rc.2 is out

**Comment by a-robinson** [comment]
Good call, done.

**Comment by a-robinson** [comment]
(to be clear, I published using the new wrangler RC after both of these changes to confirm it still works)

**Pull request merged**
