### PR TITLE
take advantage of i/o gates for counter

### PR DESCRIPTION
**Pull request by koeninger**
closes https://github.com/cloudflare/durable-objects-template/issues/11

### CODE REVIEW

**Comment by rib** [comment]
Is there automatic caching done for storage? Otherwise it doesn't seem ideal for a template that the common '/' read path will hit the storage API instead of simply reading from a `this.value` cache like before?

**Comment by koeninger** [comment]
@rib refer to https://developers.cloudflare.com/workers/learning/using-durable-objects#accessing-persistent-storage-from-a-durable-object
Bullet point starting "The storage API implements an in-memory caching layer..."

**Review by a-robinson — APPROVED** [review]
LGTM, although we also should update the other couple DO templates.

**Comment by a-robinson** [comment]
Created similar PRs on the other templates.

**Comment by kentonv** [comment]
Should we maybe add some comments in the code explaining why this works? So that we don't get a bunch of bug reports saying that we have race conditions / bad performance? :)

**Comment by kentonv** [comment]
My thought with the comment was not that we'd just link people to a long blog post but try to explain what's happening in context. Example code really should be full of detailed comments IMO. I'll make a PR...

**Comment by koeninger** [comment]
@kentonv ok if you want to PR to this repo, I can make the same change in the other PRs / make a new one for the counter example in the docs

**Comment by katopz** [comment]
So this mean current docs is not up to date? Or I still need `blockConcurrencyWhile` there?

https://developers.cloudflare.com/workers/learning/using-durable-objects/#in-memory-state-in-a-durable-object

image

**Comment by kentonv** [comment]
@katopz You probably need blockConcurrencyWhile() if you want to do initialization in the constructor -- as shown in that doc.

In this example code, it turns out to be easier to read the counter value at request time rather than in the constructor, and simply rely on I/O gates and caching to make it fast and correct. But many other types of applications still want to do constructor-time initialization with blockConcurrencyWhile().

**Pull request merged**
